In [1]:
import numpy as np

my_list = [5, 10, 15, 20, 25]

my_array = np.array(my_list)

print(my_array)

[ 5 10 15 20 25]


In [4]:
import numpy as np
my_list = [[1, 2], [3, 4], [5, 6]]
my_2d_array = np.array(my_list)
print(my_2d_array)

[[1 2]
 [3 4]
 [5 6]]


In [5]:
import numpy as np
zeros_matrix = np.zeros((3, 3))

# Print the matrix
print(zeros_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
