In [3]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]


In [4]:
array = np.array([1, 2, 3, 4])
print(np.sum(array))
print(np.mean(array))
print(np.std(array))

10
2.5
1.118033988749895


In [5]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))

[[19 22]
 [43 50]]


In [6]:
a = np.array([1, 2, 3])
b = 2
print(a * b)

[2 4 6]


In [8]:
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [9]:
a = np.array([1, 2, 3, 4])
b = a[2:4] # Creating a view of the array
b[0] = 100 # Modify the view
print(a)

[  1   2 100   4]
