In [1]:
#Question no 5
temperatures = [28, 32, 35, 31, 29, 30, 33, 36, 27, 25, 34, 30, 29, 37, 38, 26, 31, 35, 33, 32, 36, 34, 29, 28, 27, 35, 32, 30, 31, 33]


above_32 = [temp for temp in temperatures if temp > 32]


classification = [(temp, "Hot" if temp > 35 else "Warm" if temp >= 30 else "Cool") for temp in temperatures]


average_temp = sum(temperatures) / len(temperatures)
temp_differences = [temp - average_temp for temp in temperatures]


print("Temperatures above 32°C:", above_32)
print("Temperature classifications:", classification)
print("Temperature differences from average:", temp_differences)


Temperatures above 32°C: [35, 33, 36, 34, 37, 38, 35, 33, 36, 34, 35, 33]
Temperature classifications: [(28, 'Cool'), (32, 'Warm'), (35, 'Warm'), (31, 'Warm'), (29, 'Cool'), (30, 'Warm'), (33, 'Warm'), (36, 'Hot'), (27, 'Cool'), (25, 'Cool'), (34, 'Warm'), (30, 'Warm'), (29, 'Cool'), (37, 'Hot'), (38, 'Hot'), (26, 'Cool'), (31, 'Warm'), (35, 'Warm'), (33, 'Warm'), (32, 'Warm'), (36, 'Hot'), (34, 'Warm'), (29, 'Cool'), (28, 'Cool'), (27, 'Cool'), (35, 'Warm'), (32, 'Warm'), (30, 'Warm'), (31, 'Warm'), (33, 'Warm')]
Temperature differences from average: [-3.533333333333335, 0.466666666666665, 3.466666666666665, -0.533333333333335, -2.533333333333335, -1.533333333333335, 1.466666666666665, 4.466666666666665, -4.533333333333335, -6.533333333333335, 2.466666666666665, -1.533333333333335, -2.533333333333335, 5.466666666666665, 6.466666666666665, -5.533333333333335, -0.533333333333335, 3.466666666666665, 1.466666666666665, 0.466666666666665, 4.466666666666665, 2.466666666666665, -2.5333333333

In [3]:
#Question_no_4
import numpy as np

data = np.random.rand(10000)

mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)

min_value = np.min(data)
max_value = np.max(data)
count_greater_than_mean = np.sum(data > mean)

normalized_data = (data - min_value) / (max_value - min_value)

print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Standard Deviation: {std_dev}")
print(f"Minimum Value: {min_value}")
print(f"Maximum Value: {max_value}")
print(f"Count of values greater than the mean: {count_greater_than_mean}")
print(f"First 10 normalized values: {normalized_data[:10]}")


Mean: 0.5021251678728406
Median: 0.5031215130904784
Standard Deviation: 0.2875418931077666
Minimum Value: 0.00011197781912408722
Maximum Value: 0.9998192294424405
Count of values greater than the mean: 5018
First 10 normalized values: [0.83314307 0.47017728 0.72287529 0.44915743 0.76786216 0.20341527
 0.39402188 0.64557282 0.16312515 0.35744541]


In [4]:
#question no 3
import numpy as np

A = np.array([[2, 4, 6], [1, 3, 5], [7, 9, 11]])
B = np.array([[8, 5, 2], [7, 4, 1], [6, 3, 0]])

sum_ab = A + B
product_ab = A * B
dot_product = np.dot(A, B.T)
det_A = np.linalg.det(A)

print("Element wise sum of A and B:")
print(sum_ab)

print("\nElementwise product of A and B:")
print(product_ab)

print("\nDot product of A and B^T:")
print(dot_product)

print("\nDet of A:")
print(det_A)


Element-wise sum of A and B:
[[10  9  8]
 [ 8  7  6]
 [13 12 11]]

Element-wise product of A and B:
[[16 20 12]
 [ 7 12  5]
 [42 27  0]]

Dot product of A and B^T:
[[ 48  36  24]
 [ 33  24  15]
 [123  96  69]]

Determinant of A:
0.0


In [8]:
#question no 2
df = pd.read_csv("sales_large.csv")

total_sales = df.groupby(["Region", "Product"])["Sales"].sum()

highest_selling_product = df.groupby("Product")["Sales"].sum().idxmax()

print("Total sales for each product in each region:")
print(total_sales)
print(f"Product with highest total sales: {highest_selling_product}")


Total sales for each product in each region:
Region   Product
Central  Apples      9000
         Oranges     8000
East     Apples      5000
         Bananas     8500
         Oranges    13900
North    Apples      7200
         Bananas     9000
         Oranges     4900
South    Apples     12900
         Bananas     5100
         Oranges     3000
West     Apples     18900
         Bananas    14700
         Oranges     7500
Name: Sales, dtype: int64
Product with highest total sales: Apples


In [9]:
Question no 1
df = pd.read_csv("employees_large.csv")

average_salaries = df.groupby("Department")["Salary"].mean()

highest_salary_department = average_salaries.idxmax()

print("Average salaries by department:")
print(average_salaries)
print(f"Department with highest average salary: {highest_salary_department}")


Average salaries by department:
Department
Engineering    125000.0
Finance         78000.0
HR              68000.0
IT              57750.0
Marketing       43750.0
Name: Salary, dtype: float64
Department with highest average salary: Engineering
